name: "'Chapter She' at Babylon19"
url: "https://chaptershe.babylon19.org"

IDs:
  google: ""
  yandex: ""
  msvalidate: ""
  alexa: ""
  norton: ""
  
collections:
  pages:
    output: true
    permalink: /:path/
  partners:
    output: true
    permalink: /partners/:path/

defaults:
  -
    scope:
      path: ""
      type: "partners"
    values:
      layout: "partners"